apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookinfo-dev-productpage
  namespace: student14-bookinfo-dev
  labels:
    app: bookinfo-dev-productpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookinfo-dev-productpage
  template:
    metadata:
      labels:
        app: bookinfo-dev-productpage
    spec:
      containers:
      - name: bookinfo-dev-productpage
        image: ghcr.io/supakkavee/bookinfo-productpage:dev
        imagePullPolicy: Always
        env:
          - name: RATINGS_HOSTNAME
            value: "http://bookinfo-dev-ratings:8080"
          - name: REVIEWS_HOSTNAME
            value: "http://bookinfo-dev-reviews:8082"
          - name: DETAILS_HOSTNAME
            value: "http://bookinfo-dev-details:8081"
      imagePullSecrets:
      - name: registry-bookinfo
